# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ly8bPVFfBhyo-hf6PdgpSuYsmL7lzocu
"""



"""Question 1:

"""

print('        __________________\n       /\\\t\t  \\\n      /  \\\t\t   \\\n     /    \\     ________    \\\n    /      \\    \\   \\   \\    \\\n   /        \\    \\===\\===\\    \\\n  /\t     \\\t  \\___\\___\\    \\\n /____________\\\t\t\t\\\n/:\t      :\\_________________\\\n :\t      :\t\t\t :\n :\t      :\t\t\t :\n :\t      :\t\t\t :\n :    ____    :\t\t___\t :\n :   :    :   :\t       :_:_:\t :\n :   :\t  :   :\t       :_:_:\t :\n :   :\t  :   :\t\t\t :\n :   :\t +:   :\t\t\t :\n :   :\t  :   :\t\t\t :\n :___:____:___:__________________:')

"""Question 2:"""

a= int(input('Enter the first number: '))
b=int(input('Enter the second number: '))
if ((a==1 or a==6 or a==7 or a==12 or a==17 or a==20 or a==28 or a==33) and (b==1 or b==6 or b==7 or b==12 or b==17 or b==20 or b==28 or b==33)) :
 print('Both the colours are green')
elif ((a==2 or a==11 or a==13 or a==18 or a==19 or a==24 or a==29 or a==32)) and (b==2 or b==11 or b==13 or b==18 or b==19 or b==24 or b==29 or b==32) :
 print('Both the colours are red')
elif ((a==3 or a==10 or a==14 or a==23 or a==25 or a==30 or a==31 or a==36) and (b==3 or b==10 or b==14 or b==23 or b==25 or b==30 or b==31 or b==36)) :
 print('Both the colours are blue')
elif ((a==4 or a==9 or a==15 or a==22 or a==26 or a==35) and (b==4 or b==9 or b==15 or b==22 or b==26 or b==35)) :
  print('Both the colours are orange')
elif ((a==5 or a==8 or a==16 or a==21 or a==27 or a==34) and (b==5 or b==8 or b==16 or b==21 or b==27 or b==34)) :
  print('Both the colours are grey')
else:
    print('Colours are different')

"""Question 3"""

print('Start General Diagnosis')
print('Roboot Server to see if condition still exists')
check= input('Is this a newly installed server?')
#first check statement
if (check=='Yes') :
  print('Reset any components that may have come loose during shipping and reboot the server')
  check1=input('Does condition still exist?')
  if (check1=='No') :
   print('Record Action Taken')
   print('End')

else:
  check2=input('Were options added or was the configuration changed recently?')
  if(check2=='No'):
    print('Check for service notifications')
    print('Download the latest software and firmware from HP website')
    check3=input('Does condition still exist?')
    if(check3=='No'):
      print('Record Action Taken')
      print('End')
    else:
      print('Isolate and minimize the memory configuration')
      check4=input('Does condition still exist?')
      if(check4=='No'):
        print('Record Action Taken')
        print('End')
      else:
        print('Break server down to minimal configuration')
        check5=input('Does condition still exist?')
        if(check5=='Yes'):
          print('Troubleshoot or replace basic server spare parts')
          check6=input('Does condition still exist?')
          if(check6=='Yes'):
            print('Ensure the following information is available:')
            print('-Survey configuration form')
            print('-OS event log file')
            print('Full crash dump')
          else:
            print('Record symptom & error information on repair tag if sending back a failed part')
            print('END')
        else:
          print('Add one part at a time back to configuration to isolate faulty component')
          check7=input('Does condition still exist?')
          if(check7=='Yes'):
            print('Ensure the following information is available:')
            print('-Survey configuration form')
            print('-OS event log file')
            print('Full crash dump')
          else:
            print('Record Action Taken')
            print('END')
#outer else statement
  else:
    print('Isolate what has changed.Verify it was installed correctly.Restore server to last known working state or original shipped configuration')
    check8=input('Does condition still exist')
    if(check8=='Yes'):
      print('Isolate and minimize the memory configuration')
    else:
      print('Record action taken')
      print('End')

"""Question 4"""

input_year=int(input('Enter a year: '))
if (input_year%4==0) :
   if (input_year % 100==0) :
     if (input_year % 400==0) :
       print('This is a Leap Year')
     else:
       print('Not a leap Year')
   else:
    print('not a leap year')
else:
  print('Not a leap year')

"""Question 5"""

Amount=int(input('Enter the amount that needs to be withdrawn: '))
print('Required notes of 500 is ', Amount/500)
print('Required notes of 100 is', (Amount%500)/100)
print('Required notes of 50 is', ((Amount%500)%100)/50)
print('Required notes of 20 is', (((Amount%500)%100)%50)/20)
print('Required notes of 10 is', ((((Amount%500)%100)%50)%20)/10)
print('Required notes of 5 is', (((((Amount%500)%100)%50)%20)%10)/5)
print('Required notes of 1 is', ((((((Amount%500)%100)%50)%20)%10)%5)/1)